msg = "Have a nice daY"
print(msg)
print(msg.upper())
print(msg.lower())
print(msg.capitalize())
print(msg.title())
print(msg.swapcase())
print(msg.center(50,'/'))
print(msg.center(50))
print(msg.replace('nice', 'bad'))
print(msg.find('nice'))
print(msg.count('e'))
print(msg.startswith('h'))
print(msg.startswith('H'))
print(msg.endswith('y'))
print(msg.split())
word=msg.split()
print(word)
print(word[3])
print(word[2])
print(dir(msg))
print(type(print))
x=10
print(type(x))
print(dir(x))